on:
  push:
    branches:
      - release

name: Build and Release Bike App
jobs:
  build:
    name: Build Apps
    runs-on: macos-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%m.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Run Tests
        run: flutter test
      - name: Build Android App
        run: flutter build apk --debug
      - name: Build iOS App
        run: |
          flutter build ios --debug --no-codesign
          cd build/ios/iphoneosimulator
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
          zip -r Runner.zip Runner.app
      - name: send first time to appetize
        run: |
          if ["PUBKEY" == ""]
          then
                 curl --http1.1 https://${{ secrets.API_TOKEN }}@api.appetize.io/v1/apps -F "file=@Runner.zip" -F "platform=ios"
          fi
      - name: send to appetize
        run: |
          if ["PUBKEY" != ""]
          then
                 curl --http1.1 https://${{ secrets.API_TOKEN }}@api.appetize.io/v1/apps/{{end.PUBKEY}} -F "file=@Runner.zip" -F "platform=ios"
          fi
      env:
        PUBKEY: ${{ secrets.PUBKEY }}
      with:
        tag: ${{ env.APP_VERSION }}
        name: ${{ env.APP_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: 'build/app/outputs/apk/debug/*.apk,build/ios/iphoneosimulator/app.ipa